import { AdminUser, Company, EventData, FrameTemplate, SurveyQuestion, Tenant } from "./types";

// --- Demo Companies (22 companies, diverse sectors) ---
export const COMPANIES: Company[] = [
  // === Platinum (2) ===
  {
    id: "co-platinum-1",
    name: "キッズラーニング株式会社",
    logoUrl: "https://ui-avatars.com/api/?name=KL&background=6EC6FF&color=fff&size=80&rounded=true",
    tier: "platinum",
    tags: ["education", "cram_school", "technology", "age_4_6", "age_7_9"],
    videos: { cm15: "2ImiNUroz44", cm30: "LuZrMBdsnsY", cm60: "AfbNS_GKhPw" },
    offerText: "無料体験レッスン1ヶ月分プレゼント！",
    offerUrl: "https://example.com/kids-learning",
    couponCode: "VLSKIDS2026",
    portalPassword: "KIDS2026",
  },
  {
    id: "co-platinum-2",
    name: "すこやか保険グループ",
    logoUrl: "https://ui-avatars.com/api/?name=SH&background=A78BFA&color=fff&size=80&rounded=true",
    tier: "platinum",
    tags: ["insurance", "education", "age_0_3", "age_4_6"],
    videos: { cm15: "1DpRy6TFNVw", cm30: "i2JBcJH3f-Q", cm60: "JBeEpW8l-Mg" },
    offerText: "こども保険プラン初月無料！",
    offerUrl: "https://example.com/sukoyaka-insurance",
    couponCode: "VLSINS2026",
    portalPassword: "SUKOYAKA2026",
  },
  // === Gold (3) ===
  {
    id: "co-gold-1",
    name: "ファミリートラベル",
    logoUrl: "https://ui-avatars.com/api/?name=FT&background=FFB6C1&color=fff&size=80&rounded=true",
    tier: "gold",
    tags: ["travel", "travel_service", "nature", "food"],
    videos: { cm15: "5TJv9Zb_TtI", cm30: "TegiT5zVsyw", cm60: "gQw-vbA3L6g" },
    offerText: "家族旅行10%OFFクーポン",
    offerUrl: "https://example.com/family-travel",
    couponCode: "VLSTRIP2026",
    portalPassword: "FAMILY2026",
  },
  {
    id: "co-gold-2",
    name: "テックキッズラボ",
    logoUrl: "https://ui-avatars.com/api/?name=TK&background=34D399&color=fff&size=80&rounded=true",
    tier: "gold",
    tags: ["technology", "education", "lessons", "age_7_9", "age_10_12"],
    videos: { cm15: "dvZDkYt9TDw", cm30: "S07Ko_-Koh0", cm60: "WCyUpbfVh24" },
    offerText: "プログラミング無料体験クラス！",
    offerUrl: "https://example.com/tech-kids-lab",
    couponCode: "VLSTECH2026",
    portalPassword: "TECHKIDS2026",
  },
  {
    id: "co-gold-3",
    name: "パシャリカメラ",
    logoUrl: "https://ui-avatars.com/api/?name=PC&background=F472B6&color=fff&size=80&rounded=true",
    tier: "gold",
    tags: ["camera", "technology", "art"],
    videos: { cm15: "iBKhz7jdANQ", cm30: "1yS2yLH1iFQ", cm60: "FRkEHhiO6Qg" },
    offerText: "キッズカメラ20%OFFクーポン",
    offerUrl: "https://example.com/pashari-camera",
    couponCode: "VLSCAM2026",
    portalPassword: "PASHARI2026",
  },
  // === Silver (4) ===
  {
    id: "co-silver-1",
    name: "スポーツキッズアカデミー",
    logoUrl: "https://ui-avatars.com/api/?name=SK&background=98E4C1&color=fff&size=80&rounded=true",
    tier: "silver",
    tags: ["sports", "lessons", "education", "age_4_6", "age_7_9"],
    videos: { cm15: "dtpRYgI7w-w", cm30: "j7T1c6i33c4", cm60: "yow8PBNcINU" },
    offerText: "入会金無料キャンペーン中！",
    offerUrl: "https://example.com/sports-kids",
  },
  {
    id: "co-silver-2",
    name: "ネイチャーキャンプ",
    logoUrl: "https://ui-avatars.com/api/?name=NC&background=6EE7B7&color=fff&size=80&rounded=true",
    tier: "silver",
    tags: ["nature", "sports", "travel", "age_7_9", "age_10_12"],
    videos: { cm15: "kVINywZU7zU", cm30: "LPOyxzg7DZs", cm60: "gphwgjlRcrg" },
    offerText: "親子キャンプ体験2,000円OFF",
    offerUrl: "https://example.com/nature-camp",
  },
  {
    id: "co-silver-3",
    name: "アートワンダー教室",
    logoUrl: "https://ui-avatars.com/api/?name=AW&background=FCA5A5&color=fff&size=80&rounded=true",
    tier: "silver",
    tags: ["art", "education", "lessons", "age_4_6", "age_7_9"],
    videos: { cm15: "QfKWbAtVnoI", cm30: "1ivjnIKqKXI", cm60: "begpXbcMDck" },
    offerText: "アート体験教室1回無料！",
    offerUrl: "https://example.com/art-wonder",
  },
  {
    id: "co-silver-4",
    name: "スマイルスマホ",
    logoUrl: "https://ui-avatars.com/api/?name=SS&background=93C5FD&color=fff&size=80&rounded=true",
    tier: "silver",
    tags: ["smartphone", "technology", "age_10_12", "age_13_plus"],
    videos: { cm15: "MFrYvl8oF-Q", cm30: "j9murCTtx28", cm60: "gx13_1Oo_dE" },
    offerText: "キッズスマホプラン月額500円OFF",
    offerUrl: "https://example.com/smile-sumaho",
  },
  // === Bronze (3) ===
  {
    id: "co-bronze-1",
    name: "おいしいキッチン",
    logoUrl: "https://ui-avatars.com/api/?name=OK&background=FFE4A0&color=fff&size=80&rounded=true",
    tier: "bronze",
    tags: ["food", "food_product"],
    videos: { cm15: "ePcKFhKuKcI", cm30: "oNNhCcVj_sE", cm60: "0-aEbxBde70" },
    offerText: "お試しセット500円OFF",
    offerUrl: "https://example.com/oishii-kitchen",
  },
  {
    id: "co-bronze-2",
    name: "こどもブックス",
    logoUrl: "https://ui-avatars.com/api/?name=KB&background=FDE68A&color=fff&size=80&rounded=true",
    tier: "bronze",
    tags: ["education", "art", "age_0_3", "age_4_6"],
    videos: { cm15: "95VeF2BuLc0", cm30: "DBrHkQUmob0", cm60: "IE5uW0DpkZI" },
    offerText: "絵本セット送料無料キャンペーン",
    offerUrl: "https://example.com/kodomo-books",
  },
  {
    id: "co-bronze-3",
    name: "げんきスナック",
    logoUrl: "https://ui-avatars.com/api/?name=GS&background=FDBA74&color=fff&size=80&rounded=true",
    tier: "bronze",
    tags: ["food", "food_product", "sports"],
    videos: { cm15: "Jb2D11R5lck", cm30: "PIXzlJPeYKE", cm60: "WKZw_H8yDXE" },
    offerText: "スポーツ栄養バーお試しパック無料",
    offerUrl: "https://example.com/genki-snack",
  },
  // === 追加スポンサー10社 ===
  // Platinum追加 (2社)
  {
    id: "co-platinum-3",
    name: "美肌コスメ株式会社",
    logoUrl: "https://ui-avatars.com/api/?name=BC&background=FF6B9D&color=fff&size=80&rounded=true",
    tier: "platinum",
    tags: ["art", "other", "age_13_plus"],
    videos: { cm15: "GXc9h3hXRUk", cm30: "9Lt5ngpMj7I", cm60: "EvwRYGlJWfQ" },
    offerText: "新作コスメ初回20%OFFクーポン",
    offerUrl: "https://example.com/bihada-cosme",
    couponCode: "VLSCOSME2026",
  },
  {
    id: "co-platinum-4",
    name: "みらいアセット証券",
    logoUrl: "https://ui-avatars.com/api/?name=MA&background=1E40AF&color=fff&size=80&rounded=true",
    tier: "platinum",
    tags: ["insurance", "education", "other", "age_13_plus"],
    videos: { cm15: "0s1RLW8uLNU", cm30: "aw4VEV61OV0", cm60: "aH487wl978U" },
    offerText: "口座開設で5,000円プレゼント！",
    offerUrl: "https://example.com/mirai-asset",
    couponCode: "VLSINVEST2026",
  },
  // Gold追加 (3社)
  {
    id: "co-gold-4",
    name: "スマートドライブ自動車",
    logoUrl: "https://ui-avatars.com/api/?name=SD&background=374151&color=fff&size=80&rounded=true",
    tier: "gold",
    tags: ["technology", "travel", "other", "age_13_plus"],
    videos: { cm15: "PwotW2mtPJ8", cm30: "4Ma9hv2jnpM", cm60: "Y1XRKJspRvk" },
    offerText: "試乗予約でAmazonギフト券3,000円分",
    offerUrl: "https://example.com/smart-drive",
    couponCode: "VLSCAR2026",
  },
  {
    id: "co-gold-5",
    name: "ひかりモバイル",
    logoUrl: "https://placehold.co/80x80/0EA5E9/FFFFFF/png?text=光",
    tier: "gold",
    tags: ["smartphone", "technology", "age_10_12", "age_13_plus"],
    videos: { cm15: "hipnnaM7v4g", cm30: "MmWblLUtKcM", cm60: "2z2-plkBmpQ" },
    offerText: "乗り換えで月額2ヶ月無料！",
    offerUrl: "https://example.com/hikari-mobile",
    couponCode: "VLSMOBILE2026",
  },
  {
    id: "co-gold-6",
    name: "ゲームキングダム",
    logoUrl: "https://ui-avatars.com/api/?name=GK&background=7C3AED&color=fff&size=80&rounded=true",
    tier: "gold",
    tags: ["technology", "other", "age_7_9", "age_10_12", "age_13_plus"],
    videos: { cm15: "ETKWkMiJYk0", cm30: "hmpVg2PyMOA", cm60: "XLD9pSmKa7U" },
    offerText: "新作ゲームダウンロード30%OFF",
    offerUrl: "https://example.com/game-kingdom",
    couponCode: "VLSGAME2026",
  },
  // Silver追加 (3社)
  {
    id: "co-silver-5",
    name: "げんきドリンクラボ",
    logoUrl: "https://ui-avatars.com/api/?name=GD&background=F59E0B&color=fff&size=80&rounded=true",
    tier: "silver",
    tags: ["food", "food_product", "sports", "age_10_12", "age_13_plus"],
    videos: { cm15: "pHWrw1940Gg", cm30: "k8Z86ynLKRM", cm60: "lljqL0rKczQ" },
    offerText: "スポーツドリンク12本セット半額",
    offerUrl: "https://example.com/genki-drink",
    couponCode: "VLSDRINK2026",
  },
  {
    id: "co-silver-6",
    name: "フィットネスプラス",
    logoUrl: "https://ui-avatars.com/api/?name=FP&background=10B981&color=fff&size=80&rounded=true",
    tier: "silver",
    tags: ["sports", "lessons", "other", "age_13_plus"],
    videos: { cm15: "UiCcklvyp5Y", cm30: "KZGp3anfEoc", cm60: "krV4CwWtV2Q" },
    offerText: "ジム入会金無料＋初月半額！",
    offerUrl: "https://example.com/fitness-plus",
    couponCode: "VLSFIT2026",
  },
  {
    id: "co-silver-7",
    name: "ドリームランドトイズ",
    logoUrl: "https://ui-avatars.com/api/?name=DT&background=F97316&color=fff&size=80&rounded=true",
    tier: "silver",
    tags: ["age_0_3", "age_4_6", "age_7_9", "art", "education"],
    videos: { cm15: "k3aLTKjT6so", cm30: "f92VWkYl8CI", cm60: "28ZtISI8SOA" },
    offerText: "おもちゃセット1,500円OFFクーポン",
    offerUrl: "https://example.com/dreamland-toys",
    couponCode: "VLSTOY2026",
  },
  // Bronze追加 (2社)
  {
    id: "co-bronze-4",
    name: "リゾートステイホテルズ",
    logoUrl: "https://ui-avatars.com/api/?name=RS&background=0891B2&color=fff&size=80&rounded=true",
    tier: "bronze",
    tags: ["travel", "travel_service", "food", "nature", "age_13_plus"],
    videos: { cm15: "ucLsPQe8hag", cm30: "gQw-vbA3L6g", cm60: "gphwgjlRcrg" },
    offerText: "宿泊予約で朝食無料サービス",
    offerUrl: "https://example.com/resort-stay",
    couponCode: "VLSHOTEL2026",
  },
  {
    id: "co-bronze-5",
    name: "サクサクフードデリバリー",
    logoUrl: "https://ui-avatars.com/api/?name=SF&background=EF4444&color=fff&size=80&rounded=true",
    tier: "bronze",
    tags: ["food", "food_product", "technology", "other"],
    videos: { cm15: "k8Z86ynLKRM", cm30: "pHWrw1940Gg", cm60: "lljqL0rKczQ" },
    offerText: "初回注文送料無料＋300円OFF",
    offerUrl: "https://example.com/sakusaku-food",
    couponCode: "VLSFOOD2026",
  },
  // === Mother Vegetable (Platinum) ===
  {
    id: "co-platinum-mv",
    name: "Mother Vegetable",
    logoUrl: "/logos/co-platinum-mv.svg",
    tier: "platinum",
    tags: ["food", "food_product", "nature", "age_0_3", "age_4_6", "age_7_9", "age_10_12", "age_13_plus"],
    videos: { cm15: "LcODhoVAWUE", cm30: "nxiChGXQ8rA", cm60: "Nc1Tq5-OCog" },
    offerText: "Mother Vegetable 48栄養素サプリ お試しセット送料無料",
    offerUrl: "https://mothervegetable.com",
    couponCode: "VLSMV2026",
    portalPassword: "MOTHER2026",
  },
];

// --- Demo Events ---
export const DEFAULT_FRAME_TEMPLATES: FrameTemplate[] = [
  {
    id: "frame-default",
    name: "デフォルトフレーム",
    url: "/frame-template.svg",
    isActive: true,
    createdAt: Date.parse("2026-03-11T00:00:00+09:00"),
    updatedAt: Date.parse("2026-03-11T00:00:00+09:00"),
  },
];

export const EVENTS: EventData[] = [
  {
    id: "evt-summer",
    name: "夏祭り 2026",
    date: "2026-08-15",
    description: "楽しい夏祭りイベント",
    password: "SUMMER2026",
    photos: generateDemoPhotos("summer", 12),
    slug: "summer2026",
    tenantId: "tenant-school-a",
    // All companies (undefined = no filter)
  },
  {
    id: "evt-sports",
    name: "運動会 2026",
    date: "2026-10-10",
    description: "秋の大運動会",
    password: "SPORTS2026",
    photos: generateDemoPhotos("sports", 9),
    slug: "sports2026",
    tenantId: "tenant-school-a",
    companyIds: ["co-platinum-mv", "co-platinum-1", "co-gold-2", "co-silver-1", "co-silver-2", "co-bronze-3", "co-silver-5", "co-silver-6"],
  },
  {
    id: "evt-graduation",
    name: "卒業式 2026",
    date: "2026-03-20",
    description: "感動の卒業式",
    password: "GRADUATION2026",
    photos: generateDemoPhotos("graduation", 15),
    slug: "graduation2026",
    tenantId: "tenant-school-b",
    companyIds: ["co-platinum-mv", "co-platinum-1", "co-platinum-2", "co-gold-3", "co-silver-1", "co-silver-3", "co-bronze-2", "co-platinum-3", "co-silver-7", "co-bronze-4"],
  },
  {
    id: "evt-techfes",
    name: "テクノロジーフェス 2026",
    date: "2026-11-23",
    description: "最新テクノロジー体験イベント",
    password: "TECHFES2026",
    photos: generateDemoPhotos("techfes", 10),
    slug: "techfes2026",
    tenantId: "tenant-corp-a",
    companyIds: [
      "co-platinum-mv", "co-platinum-3", "co-platinum-4",
      "co-gold-4", "co-gold-5", "co-gold-6",
      "co-silver-4", "co-silver-5", "co-silver-6",
      "co-bronze-4", "co-bronze-5",
    ],
  },
];

function generateDemoPhotos(seed: string, count: number): EventData["photos"] {
  return Array.from({ length: count }, (_, i) => ({
    id: `${seed}-photo-${i + 1}`,
    originalUrl: `https://picsum.photos/seed/${seed}${i + 1}/1200/800`,
    thumbnailUrl: `https://picsum.photos/seed/${seed}${i + 1}/400/300`,
    watermarked: true,
  }));
}

// --- Password → Event Mapping ---
export function getEventByPassword(password: string): EventData | null {
  return EVENTS.find((e) => e.password === password.toUpperCase()) || null;
}

// --- Default Survey ---
export const DEFAULT_SURVEY: SurveyQuestion[] = [
  {
    id: "q1",
    question: "親子で興味があるテーマは？",
    maxSelections: 3,
    options: [
      { label: "教育", tag: "education" },
      { label: "スポーツ", tag: "sports" },
      { label: "食", tag: "food" },
      { label: "旅行", tag: "travel" },
      { label: "テクノロジー", tag: "technology" },
      { label: "アート", tag: "art" },
      { label: "自然", tag: "nature" },
      { label: "その他", tag: "other" },
    ],
  },
  {
    id: "q2",
    question: "気になるサービスは？",
    maxSelections: 3,
    options: [
      { label: "学習塾", tag: "cram_school" },
      { label: "習い事", tag: "lessons" },
      { label: "食品", tag: "food_product" },
      { label: "旅行", tag: "travel_service" },
      { label: "スマホ", tag: "smartphone" },
      { label: "カメラ", tag: "camera" },
      { label: "保険", tag: "insurance" },
      { label: "その他", tag: "other" },
    ],
  },
  {
    id: "q3",
    question: "お子様の年齢は？",
    maxSelections: 1,
    options: [
      { label: "0〜3歳", tag: "age_0_3" },
      { label: "4〜6歳", tag: "age_4_6" },
      { label: "7〜9歳", tag: "age_7_9" },
      { label: "10〜12歳", tag: "age_10_12" },
      { label: "13歳以上", tag: "age_13_plus" },
    ],
  },
];

// --- Demo Tenants ---
export const TENANTS: Tenant[] = [
  {
    id: "tenant-school-a",
    name: "さくら学園",
    slug: "sakura",
    adminPassword: "SAKURA_ADMIN_2026",
    plan: "premium",
    contactEmail: "admin@sakura-gakuen.example.com",
    contactName: "田中 太郎",
    billingAddress: "東京都渋谷区桜丘1-2-3",
    invoicePrefix: "INV-SAKURA",
    createdAt: 1700000000000,
    licenseStart: "2026-01-01",
    licenseEnd: "2026-12-31",
    maxEvents: 10,
    isActive: true,
  },
  {
    id: "tenant-school-b",
    name: "ひまわり幼稚園",
    slug: "himawari",
    adminPassword: "HIMAWARI_ADMIN_2026",
    plan: "basic",
    contactEmail: "info@himawari.example.com",
    contactName: "佐藤 花子",
    billingAddress: "大阪府大阪市北区梅田4-5-6",
    invoicePrefix: "INV-HIMAWARI",
    createdAt: 1700000000000,
    licenseStart: "2026-04-01",
    licenseEnd: "2026-09-30",
    maxEvents: 3,
    isActive: true,
  },
  {
    id: "tenant-corp-a",
    name: "株式会社イベントプロ",
    slug: "eventpro",
    adminPassword: "EVENTPRO_ADMIN_2026",
    plan: "enterprise",
    contactEmail: "billing@eventpro.example.com",
    contactName: "山田 次郎",
    billingAddress: "東京都千代田区丸の内7-8-9",
    invoicePrefix: "INV-EP",
    createdAt: 1700000000000,
    licenseStart: "2025-10-01",
    licenseEnd: "2027-03-31",
    maxEvents: 50,
    isActive: true,
  },
];

export const DEFAULT_ADMIN_USERS: AdminUser[] = [
  {
    id: "viewer-sakura",
    name: "さくら学園 閲覧者",
    password: "VIEW_SAKURA",
    role: "viewer",
    tenantId: "tenant-sakura",
    permissions: ["events.read", "companies.read", "photos.read", "users.read", "analytics.read"],
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "viewer-himawari",
    name: "ひまわり幼稚園 閲覧者",
    password: "VIEW_HIMAWARI",
    role: "viewer",
    tenantId: "tenant-himawari",
    permissions: ["events.read", "companies.read", "photos.read", "users.read", "analytics.read"],
    isActive: true,
    createdAt: Date.now(),
  },
];

export { ADMIN_PASSWORD } from "./constants";
