"use client";

import { useEffect, useRef, useState } from "react";
import { jsPDF } from "jspdf";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import { InvoiceData, InvoiceItem, Tenant } from "@/lib/types";
import {
  getStoredTenants, getStoredEvents, getStoredAnalytics,
  getStoredInvoices, setStoredInvoices,
} from "@/lib/store";
import { IS_DEMO_MODE } from "@/lib/demo";

const inputCls = "w-full px-3 py-2 rounded-xl border border-gray-200 focus:border-[#6EC6FF] focus:outline-none text-sm";

const STATUS_COLORS: Record<InvoiceData["status"], string> = {
  draft: "bg-gray-100 text-gray-600",
  issued: "bg-blue-100 text-blue-700",
  paid: "bg-green-100 text-green-700",
};

const PRICING = {
  eventBase: 50000,
  cmSlotPlatinum: 30000,
  cmSlotGold: 20000,
  cmSlotSilver: 10000,
  perParticipant: 100,
  photoStorage: 5000,
};

function formatYen(n: number): string {
  return `¥${n.toLocaleString()}`;
}

function generateInvoicePdf(invoice: InvoiceData, tenant: Tenant | undefined) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const w = 210;
  let y = 20;

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", w / 2, y, { align: "center" });
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice #: ${invoice.id}`, 15, y);
  doc.text(`Date: ${invoice.issueDate}`, w - 15, y, { align: "right" });
  y += 5;
  doc.text(`Status: ${invoice.status.toUpperCase()}`, 15, y);
  doc.text(`Due: ${invoice.dueDate}`, w - 15, y, { align: "right" });
  y += 10;

  // From
  doc.setFont("helvetica", "bold");
  doc.text("From:", 15, y);
  doc.setFont("helvetica", "normal");
  doc.text("VLS System - Event Photo Service", 30, y);
  y += 5;
  doc.text("noreply@vls-system.vercel.app", 30, y);
  y += 10;

  // To
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", 15, y);
  doc.setFont("helvetica", "normal");
  doc.text(tenant?.name || "N/A", 35, y);
  y += 5;
  doc.text(tenant?.contactName || "", 35, y);
  y += 5;
  doc.text(tenant?.contactEmail || "", 35, y);
  y += 5;
  if (tenant?.billingAddress) {
    doc.text(tenant.billingAddress, 35, y);
    y += 5;
  }
  y += 8;

  // Table header
  doc.setFillColor(240, 240, 245);
  doc.rect(15, y - 3, w - 30, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("Description", 18, y + 2);
  doc.text("Qty", 115, y + 2, { align: "center" });
  doc.text("Unit Price", 145, y + 2, { align: "right" });
  doc.text("Amount", w - 18, y + 2, { align: "right" });
  y += 10;

  // Table rows
  doc.setFont("helvetica", "normal");
  for (const item of invoice.items) {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    doc.text(item.description.slice(0, 50), 18, y);
    doc.text(String(item.quantity), 115, y, { align: "center" });
    doc.text(formatYen(item.unitPrice), 145, y, { align: "right" });
    doc.text(formatYen(item.amount), w - 18, y, { align: "right" });
    y += 6;
  }

  y += 4;
  doc.line(15, y, w - 15, y);
  y += 8;

  // Totals
  doc.setFontSize(10);
  doc.text("Subtotal:", 135, y, { align: "right" });
  doc.text(formatYen(invoice.subtotal), w - 18, y, { align: "right" });
  y += 6;
  doc.text(`Tax (${invoice.taxRate}%):`, 135, y, { align: "right" });
  doc.text(formatYen(invoice.taxAmount), w - 18, y, { align: "right" });
  y += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("TOTAL:", 135, y, { align: "right" });
  doc.text(formatYen(invoice.grandTotal), w - 18, y, { align: "right" });
  y += 12;

  if (invoice.notes) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Notes: " + invoice.notes, 15, y);
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by VLS System - Event Photo Service", w / 2, 285, { align: "center" });

  doc.save(`Invoice_${invoice.id}.pdf`);
}

export default function InvoiceGenerator({ onSave }: { onSave: (msg: string) => void }) {
  const [invoices, setInvoices] = useState<InvoiceData[]>([]);
  const [tenants, setTenants] = useState<Tenant[]>([]);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ tenantId: "", notes: "", taxRate: 10 });
  const [items, setItems] = useState<InvoiceItem[]>([]);
  const descRef = useRef<HTMLInputElement>(null);
  const qtyRef = useRef<HTMLInputElement>(null);
  const priceRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setInvoices(getStoredInvoices());
    setTenants(getStoredTenants());
  }, []);

  const events = getStoredEvents();
  const analytics = getStoredAnalytics();

  const startCreate = () => {
    setCreating(true);
    setForm({ tenantId: "", notes: "", taxRate: 10 });
    setItems([]);
  };

  const addItem = (desc: string, qty: number, unitPrice: number) => {
    setItems([...items, { description: desc, quantity: qty, unitPrice, amount: qty * unitPrice }]);
  };

  const removeItem = (idx: number) => {
    setItems(items.filter((_, i) => i !== idx));
  };

  const autoGenerateItems = () => {
    if (!form.tenantId) return;
    const tenantEvents = events.filter((e) => e.tenantId === form.tenantId);
    const newItems: InvoiceItem[] = [];

    for (const evt of tenantEvents) {
      newItems.push({
        description: `Event fee: ${evt.name}`,
        quantity: 1,
        unitPrice: PRICING.eventBase,
        amount: PRICING.eventBase,
      });

      const evtAnalytics = analytics.filter((a) => a.eventId === evt.id);
      if (evtAnalytics.length > 0) {
        newItems.push({
          description: `Participants: ${evt.name} (${evtAnalytics.length} users)`,
          quantity: evtAnalytics.length,
          unitPrice: PRICING.perParticipant,
          amount: evtAnalytics.length * PRICING.perParticipant,
        });
      }

      if (evt.photos.length > 0) {
        newItems.push({
          description: `Photo storage: ${evt.name} (${evt.photos.length} photos)`,
          quantity: 1,
          unitPrice: PRICING.photoStorage,
          amount: PRICING.photoStorage,
        });
      }
    }

    setItems(newItems);
  };

  const saveInvoice = () => {
    if (!form.tenantId || items.length === 0) return;
    const subtotal = items.reduce((s, i) => s + i.amount, 0);
    const taxAmount = Math.round(subtotal * form.taxRate / 100);
    const tenant = tenants.find((t) => t.id === form.tenantId);
    const prefix = tenant?.invoicePrefix || "INV";
    const tenantEvents = events.filter((e) => e.tenantId === form.tenantId);

    const invoice: InvoiceData = {
      id: `${prefix}-${Date.now().toString(36).toUpperCase()}`,
      tenantId: form.tenantId,
      eventIds: tenantEvents.map((e) => e.id),
      issueDate: new Date().toISOString().slice(0, 10),
      dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      items,
      subtotal,
      taxRate: form.taxRate,
      taxAmount,
      grandTotal: subtotal + taxAmount,
      status: "draft",
      notes: form.notes || undefined,
      createdAt: Date.now(),
    };

    const updated = [...invoices, invoice];
    setStoredInvoices(updated);
    setInvoices(updated);
    setCreating(false);
    onSave("請求書を作成しました");
  };

  const downloadPdf = (invoice: InvoiceData) => {
    const tenant = tenants.find((t) => t.id === invoice.tenantId);
    generateInvoicePdf(invoice, tenant);
  };

  const updateStatus = (id: string, status: InvoiceData["status"]) => {
    const updated = invoices.map((inv) => inv.id === id ? { ...inv, status } : inv);
    setStoredInvoices(updated);
    setInvoices(updated);
    onSave(`ステータスを${status}に更新しました`);
  };

  const deleteInvoice = (id: string) => {
    const updated = invoices.filter((inv) => inv.id !== id);
    setStoredInvoices(updated);
    setInvoices(updated);
    onSave("請求書を削除しました");
  };

  const subtotal = items.reduce((s, i) => s + i.amount, 0);
  const taxAmount = Math.round(subtotal * form.taxRate / 100);
  const grandTotal = subtotal + taxAmount;

  return (
    <div className="space-y-4" data-testid="admin-invoices">
      <div className="flex justify-between items-center">
        <h2 className="text-lg font-bold text-gray-800">請求書管理</h2>
        {!IS_DEMO_MODE && <Button size="sm" onClick={startCreate}>+ 新規請求書</Button>}
      </div>

      {creating && (
        <Card>
          <h3 className="font-bold text-gray-700 mb-3">請求書作成</h3>
          <div className="space-y-3">
            <div>
              <label className="text-xs text-gray-500 block mb-1">請求先テナント</label>
              <select className={inputCls} value={form.tenantId} onChange={(e) => setForm({ ...form, tenantId: e.target.value })} data-testid="invoice-tenant-select">
                <option value="">テナントを選択...</option>
                {tenants.map((t) => (
                  <option key={t.id} value={t.id}>{t.name} ({t.plan})</option>
                ))}
              </select>
            </div>

            {form.tenantId && (
              <button onClick={autoGenerateItems} className="text-xs px-3 py-1.5 rounded-lg bg-purple-500 text-white hover:bg-purple-600 font-medium">
                イベント実績から自動計算
              </button>
            )}

            {items.length > 0 && (
              <div className="border rounded-lg overflow-hidden">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="bg-gray-50 border-b">
                      <th className="p-2 text-left">項目</th>
                      <th className="p-2 text-center w-16">数量</th>
                      <th className="p-2 text-right w-24">単価</th>
                      <th className="p-2 text-right w-24">金額</th>
                      <th className="p-2 w-8"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {items.map((item, i) => (
                      <tr key={i} className="border-b">
                        <td className="p-2">{item.description}</td>
                        <td className="p-2 text-center">{item.quantity}</td>
                        <td className="p-2 text-right font-mono">{formatYen(item.unitPrice)}</td>
                        <td className="p-2 text-right font-mono font-bold">{formatYen(item.amount)}</td>
                        <td className="p-2 text-center">
                          <button onClick={() => removeItem(i)} className="text-red-400 hover:text-red-600">×</button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="bg-gray-50 border-t">
                      <td colSpan={3} className="p-2 text-right font-bold text-gray-600">小計</td>
                      <td className="p-2 text-right font-mono font-bold">{formatYen(subtotal)}</td>
                      <td></td>
                    </tr>
                    <tr className="bg-gray-50">
                      <td colSpan={3} className="p-2 text-right text-gray-500">消費税 ({form.taxRate}%)</td>
                      <td className="p-2 text-right font-mono">{formatYen(taxAmount)}</td>
                      <td></td>
                    </tr>
                    <tr className="bg-blue-50 border-t-2 border-blue-200">
                      <td colSpan={3} className="p-2 text-right font-bold text-blue-700">合計</td>
                      <td className="p-2 text-right font-mono font-bold text-blue-700">{formatYen(grandTotal)}</td>
                      <td></td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            )}

            {/* Manual item add */}
            <div className="flex gap-2 items-end">
              <div className="flex-1">
                <label className="text-[10px] text-gray-400">項目名</label>
                <input ref={descRef} className={inputCls} placeholder="CM枠料金 etc." />
              </div>
              <div className="w-16">
                <label className="text-[10px] text-gray-400">数量</label>
                <input ref={qtyRef} className={inputCls} type="number" defaultValue={1} />
              </div>
              <div className="w-24">
                <label className="text-[10px] text-gray-400">単価(円)</label>
                <input ref={priceRef} className={inputCls} type="number" placeholder="10000" />
              </div>
              <button
                onClick={() => {
                  const desc = descRef.current?.value || "";
                  const qty = parseInt(qtyRef.current?.value || "1") || 1;
                  const price = parseInt(priceRef.current?.value || "0") || 0;
                  if (desc && price > 0) {
                    addItem(desc, qty, price);
                    if (descRef.current) descRef.current.value = "";
                    if (priceRef.current) priceRef.current.value = "";
                  }
                }}
                className="text-xs px-3 py-2 rounded-lg bg-gray-200 hover:bg-gray-300 font-medium whitespace-nowrap"
              >
                + 追加
              </button>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs text-gray-500 block mb-1">税率 (%)</label>
                <input className={inputCls} type="number" value={form.taxRate} onChange={(e) => setForm({ ...form, taxRate: parseInt(e.target.value) || 0 })} />
              </div>
              <div>
                <label className="text-xs text-gray-500 block mb-1">備考</label>
                <input className={inputCls} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="お支払い期限: 発行日から30日以内" />
              </div>
            </div>

            <div className="flex gap-2">
              <Button size="sm" onClick={saveInvoice} disabled={items.length === 0 || !form.tenantId}>
                請求書を保存
              </Button>
              <Button size="sm" variant="secondary" onClick={() => setCreating(false)}>キャンセル</Button>
            </div>
          </div>
        </Card>
      )}

      {/* Invoice list */}
      {invoices.length === 0 && !creating ? (
        <Card>
          <p className="text-sm text-gray-400 text-center py-6">請求書がありません</p>
        </Card>
      ) : (
        [...invoices].sort((a, b) => b.createdAt - a.createdAt).map((inv) => {
          const tenant = tenants.find((t) => t.id === inv.tenantId);
          return (
            <Card key={inv.id}>
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-mono font-bold text-gray-800 text-sm">{inv.id}</span>
                    <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold ${STATUS_COLORS[inv.status]}`}>
                      {inv.status === "draft" ? "下書き" : inv.status === "issued" ? "発行済" : "入金済"}
                    </span>
                  </div>
                  <p className="text-xs text-gray-500">
                    {tenant?.name || inv.tenantId} | {inv.issueDate} | {inv.items.length}項目
                  </p>
                  <p className="text-lg font-bold text-gray-800 mt-1">{formatYen(inv.grandTotal)}</p>
                </div>
                <div className="flex gap-2 items-center">
                  {inv.status === "draft" && (
                    <button onClick={() => updateStatus(inv.id, "issued")} className="text-xs px-2 py-1 rounded bg-blue-100 text-blue-700 hover:bg-blue-200 font-medium">
                      発行
                    </button>
                  )}
                  {inv.status === "issued" && (
                    <button onClick={() => updateStatus(inv.id, "paid")} className="text-xs px-2 py-1 rounded bg-green-100 text-green-700 hover:bg-green-200 font-medium">
                      入金済
                    </button>
                  )}
                  <button onClick={() => downloadPdf(inv)} className="text-xs px-2 py-1 rounded bg-purple-100 text-purple-700 hover:bg-purple-200 font-medium">
                    PDF
                  </button>
                  {!IS_DEMO_MODE && (
                    <button onClick={() => deleteInvoice(inv.id)} className="text-xs text-red-400 hover:text-red-600">
                      削除
                    </button>
                  )}
                </div>
              </div>
            </Card>
          );
        })
      )}
    </div>
  );
}
